.catalog:
  name: "ISDPA Single"
  version: v0.7
  description: |
    ISDPA Single Node
  questions:
    - variable: "mysql_root_password"
      type: string
      required: true
      label: "MySQL Root Password"
      description: "Password given to the root mysql user"
    - variable: "mysql_database"
      type: string
      required: true
      label: "MySQL Database Name"
      description: "MySQL database to create"
    - variable: "mysql_user"
      type: string
      required: true
      description: "MySQL user for the created database"
      label: "MySQL DB User"
    - variable: "mysql_password"
      type: string
      required: true
      label: "MySQL DB Password"
      description: "Password for the MySQL user of the created database"
    - variable: "mysql_allias_name"
      type: string
      required: true
      label: "MySQL DB allias"
      description: "MySQL DB allias in settings.php on site"
    - variable: "drupal_port"
       description: "Публичный порт Друпала"
       label: "Drupal port on host"
       required: true
       type: "int"
       default: 10777
    - variable: "host_label"
       label: "Host label"
       description: "Specify a Rancher host label here that will be used to determine where the service is deploy. This will determine what hosts can access the volumes managed by this stack. Default is location.dc=Azure"
       type: "string"
       default: location.dc=Azure
       required: true
mariadb:
  scale: 1
drupal:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
